#+TITLE:L3ProAII Régulation Industrielle -  TP Régulation de temperature de l'eau d'un bac.
#+AUTHOR:BOUFADENE Mehdi COUTAUD Ulysse
#+DATE:<2022-03-30 Wed>
# #+LATEX_HEADER:\usepackage[margin=0.7in]{geometry}
#+LATEX: \newpage

* Prise en main et première simulation de picking
** Mise en place d'une scène basique
+ Nous avons mis en place une scène basique pour un premier scénario de simulation d'un robot.
TODO Figure 1.
+ Le robot placé au centre est équipé d'une pince non-commandable.
+ Le robot est entouré par 2 tapis-roulants qui seront les zones de prise et de dépose des objets.
+ Nous avons positionné le repère UTool de la pince installé sur le robot en extrémité de ces pinces.
+ Les zones de dépot sont bien dans la zone de travail du robot équipé de cette pince et vis à vis du point de repère Utool de cette pince.
TODO figure 2.           
+ Nous avons positionné 2 boites sur les tapis et avons paramétré leu orientation de manière à ce que le robot puisse se positionner pour les attraper par le haut.
TODO figure 3: le robot en position d'interaction avec la boite sur le plateau 1
TODO figure 4: le robot en position d'interaction avec la boite sur le plateau 2

** Programme et simulation d'un programme de picking simple

